apiVersion: v1
kind: ConfigMap
metadata:
  name: intake-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: glerp-ai-intake
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
