apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "glerp-sec-audit.fullname" . }}-scanner
  labels:
    {{- include "glerp-sec-audit.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-bench
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "glerp-sec-audit.fullname" . }}-scanner
subjects:
  - kind: ServiceAccount
    name: {{ include "glerp-sec-audit.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
