apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "glerp-sec-audit.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glerp-sec-audit.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-bench
